# Generated by Django 5.2.5 on 2025-08-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
    ]
