# Generated by Django 5.2.5 on 2025-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
