# Generated by Django 5.2.5 on 2025-09-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0007_category_advertisement_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='ads', to='board_app.tag', verbose_name='Теги'),
        ),
    ]
