# Generated by Django 5.2.5 on 2025-09-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0009_advertisement_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
