# Generated by Django 5.2.5 on 2025-10-07 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0011_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_ads', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
