# Generated by Django 5.2.5 on 2025-11-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0014_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_important', models.BooleanField(verbose_name='Важные новости')),
                ('news_type', models.CharField(choices=[('announcement', 'Реклама'), ('update', 'Обновление'), ('event', 'Событие'), ('maintenence', 'Технические работы')], verbose_name='Тип новости')),
                ('pinned', models.BooleanField(verbose_name='Закрепленная новость')),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_item', to='board_app.advertisement', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'ads_news',
            },
        ),
    ]
