# Generated by Django 5.2.5 on 2025-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0015_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('announcement', 'Реклама'), ('update', 'Новинка'), ('event', 'Событие'), ('maintenence', 'Технические работы')], verbose_name='Тип новости'),
        ),
    ]
